# config for api responses

responses:
  success:
    code: 0
    message: Success

  getRecordsFail:
    code: 1
    message: Failed to get records

  validationFail:
    code: 2
    message: Payload validation failed



    